/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/governance/catalog': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Catalog
     * @description Return catalog entries generated from registered domain metadata.
     */
    get: operations['get_catalog_api_v1_governance_catalog_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/nlq/ask': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Ask Nlq
     * @description Run the NLQ flow from intent parsing to read-only execution.
     */
    post: operations['ask_nlq_api_v1_nlq_ask_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Root */
    get: operations['read_root__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Check */
    get: operations['health_check_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * CatalogEntry
     * @description Catalog projection built from a registered domain dataset.
     */
    CatalogEntry: {
      /** Domain Id */
      domain_id: string
      /** Dataset */
      dataset: string
      layer: components['schemas']['DataLayer']
      /** Schema Version */
      schema_version: string
      /** Description */
      description: string
      /** Fields */
      fields: components['schemas']['FieldDefinition'][]
    }
    /**
     * DataLayer
     * @description Logical data-lake layers exposed to domain implementations.
     * @enum {string}
     */
    DataLayer: 'bronze' | 'silver' | 'gold'
    /**
     * FieldDefinition
     * @description Portable field metadata used by catalog and NLQ consumers.
     */
    FieldDefinition: {
      /** Name */
      name: string
      /** Data Type */
      data_type: string
      /**
       * Nullable
       * @default true
       */
      nullable: boolean
      /**
       * Description
       * @default
       */
      description: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * NaturalLanguageQueryRequest
     * @description User question submitted to the NLQ engine.
     */
    NaturalLanguageQueryRequest: {
      /** Question */
      question: string
    }
    /**
     * NaturalLanguageQueryResponse
     * @description NLQ response payload.
     */
    NaturalLanguageQueryResponse: {
      /** Sql */
      sql: string
      /**
       * Rows
       * @default []
       */
      rows: {
        [key: string]: unknown
      }[]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_catalog_api_v1_governance_catalog_get: {
    parameters: {
      query?: {
        domain_id?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogEntry'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  ask_nlq_api_v1_nlq_ask_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NaturalLanguageQueryRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NaturalLanguageQueryResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_root__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  health_check_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
