#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE SCHEMA IF NOT EXISTS app  AUTHORIZATION "$POSTGRES_USER";
CREATE SCHEMA IF NOT EXISTS gold AUTHORIZATION "$POSTGRES_USER";

CREATE ROLE "$DB_READONLY_USER" LOGIN PASSWORD '$DB_READONLY_PASSWORD';
GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$DB_READONLY_USER";
GRANT USAGE ON SCHEMA gold TO "$DB_READONLY_USER";
GRANT SELECT ON ALL TABLES IN SCHEMA gold TO "$DB_READONLY_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER" IN SCHEMA gold
  GRANT SELECT ON TABLES TO "$DB_READONLY_USER";
ALTER ROLE "$DB_READONLY_USER" SET default_transaction_read_only = on;
ALTER ROLE "$DB_READONLY_USER" SET statement_timeout = '${DB_STATEMENT_TIMEOUT_MS}ms';
ALTER ROLE "$DB_READONLY_USER" SET search_path = gold;

CREATE DATABASE "$DB_SOURCE_NAME" OWNER "$POSTGRES_USER";
EOSQL
